In [2]:
import numpy as np

## DataTypes and Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
# number elements in each ndarray
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a dataframe from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df


0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Create arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2 ,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3 ,5))
random_array

array([[3, 1, 7, 2, 8],
       [8, 8, 0, 5, 4],
       [8, 1, 6, 0, 3]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [29]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.38605953, 0.38125406, 0.53086363],
       [0.44273267, 0.4368819 , 0.09383458],
       [0.94278833, 0.1608122 , 0.17287884],
       [0.50284482, 0.58156771, 0.6577746 ],
       [0.66397282, 0.57932651, 0.20278091]])

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.84244368, 0.76943292, 0.36415069],
       [0.83959568, 0.82996495, 0.02548793],
       [0.82661081, 0.1855734 , 0.64299843],
       [0.83788632, 0.51238781, 0.38754667],
       [0.7840957 , 0.06324094, 0.29798119]])

In [32]:
random_array_3.shape

(5, 3)

In [42]:
# Pseudo-random numbers - Since seed = 0, 
# the random numbers won't change for every execution for create random numbers
# the seed could be any number. e.g. 0, 34, 888, 99999
np.random.seed(seed=99999)
randaom_array_4 = np.random.randint(10, size = (5 ,3))
randaom_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## Viewing arrays and matrices

In [43]:
np.unique(randaom_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [44]:
a1

array([1, 2, 3])

In [45]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [48]:
a3[:2, :2, :1]

array([[[ 1],
        [ 4]],

       [[10],
        [13]]])

In [52]:
a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [53]:
a3[1, :2, :2]


array([[10, 11],
       [13, 14]])

In [54]:
a3[0, :2, :2]

array([[1, 2],
       [4, 5]])

In [55]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[2, 0, 0, 5, 0],
         [0, 8, 1, 0, 9],
         [7, 1, 8, 9, 5],
         [8, 3, 4, 2, 1]],

        [[5, 5, 8, 3, 4],
         [6, 9, 6, 9, 4],
         [6, 5, 5, 8, 8],
         [7, 4, 0, 9, 2]],

        [[0, 7, 2, 8, 1],
         [2, 9, 4, 4, 4],
         [3, 3, 4, 1, 0],
         [1, 3, 0, 5, 8]]],


       [[[7, 7, 5, 4, 6],
         [8, 7, 6, 4, 7],
         [4, 4, 4, 2, 5],
         [7, 2, 2, 0, 8]],

        [[1, 5, 5, 5, 6],
         [9, 0, 7, 7, 6],
         [2, 5, 0, 9, 1],
         [0, 6, 9, 9, 3]],

        [[2, 3, 2, 4, 0],
         [6, 0, 2, 0, 6],
         [9, 5, 4, 1, 7],
         [5, 7, 8, 2, 7]]]])

In [56]:
a4.shape

(2, 3, 4, 5)

In [57]:
a4.ndim

4

In [58]:
a4[1][1][0]

array([1, 5, 5, 5, 6])

In [59]:
# get 4 most numbers of inner most array
a4[:, :, :, :4]

array([[[[2, 0, 0, 5],
         [0, 8, 1, 0],
         [7, 1, 8, 9],
         [8, 3, 4, 2]],

        [[5, 5, 8, 3],
         [6, 9, 6, 9],
         [6, 5, 5, 8],
         [7, 4, 0, 9]],

        [[0, 7, 2, 8],
         [2, 9, 4, 4],
         [3, 3, 4, 1],
         [1, 3, 0, 5]]],


       [[[7, 7, 5, 4],
         [8, 7, 6, 4],
         [4, 4, 4, 2],
         [7, 2, 2, 0]],

        [[1, 5, 5, 5],
         [9, 0, 7, 7],
         [2, 5, 0, 9],
         [0, 6, 9, 9]],

        [[2, 3, 2, 4],
         [6, 0, 2, 0],
         [9, 5, 4, 1],
         [5, 7, 8, 2]]]])

In [60]:
a4[:, :, :, :3]

array([[[[2, 0, 0],
         [0, 8, 1],
         [7, 1, 8],
         [8, 3, 4]],

        [[5, 5, 8],
         [6, 9, 6],
         [6, 5, 5],
         [7, 4, 0]],

        [[0, 7, 2],
         [2, 9, 4],
         [3, 3, 4],
         [1, 3, 0]]],


       [[[7, 7, 5],
         [8, 7, 6],
         [4, 4, 4],
         [7, 2, 2]],

        [[1, 5, 5],
         [9, 0, 7],
         [2, 5, 0],
         [0, 6, 9]],

        [[2, 3, 2],
         [6, 0, 2],
         [9, 5, 4],
         [5, 7, 8]]]])